using System;

using Hadouken.Contracts;

namespace Hadouken.Commands
{
	public class AolSayCommand : ICommand
	{
        private static readonly Random Random = new Random();
	
		private static string[] Responses =
		{
			"THERE'S AN ASSNUGGET 4 ALL YA JEWS AND HOMERSEXULES",
			"A DIQ IZ FER DISPENISING JIZZJ00CE IN DA CLITSAQ JIZZPOQIT",
			"AOL E_MAILWAREZ IS 2 31337 FOR THE CLITSAQLIKES OFF MIZZEE",
			"SIMPSONS WIN95 THEME R0X! THOT I'D LET Y'ALL KNOW",
			"ITZ UHBOWT THAT TYME 4 ME 2 OHPEN UP THA P00PYTANG AND LET THA JIZPEACHBANANAHOLEJ00ZEZ PHLOE.",
			"EYE KAN SPEEK IN MANNY DIVVRUNT LUNGAGAGES , MUCHAHASAQ",
			"SO, WHAT YOUR SAYING IS THE ECCENTRICITY OF THE AFORENAMED SAQ IS BEYOND A REASONABLE DOUBT, THE CORNACOPIA OF THE PLETHORA OF GENTALIA? DAYOM EYEM SMAERT!",
			"WHAT UR J00 TOO FRAID UV DA UREET AOL_MAN?",
			"J00 N0 FUX WIF ME! EYE'LL BUST J00 IN THA GRILL NIG-NUGGET!",
			"MUH MUDDAH SAD THAT SHE LYKES AOL CUZ OF ITZ CHATREWMZ AND SHIT BUT I LIKE CHAAATTINNG WITH YOU GUYS ON EYEARSEE AND DOWNLOADING NEKKKED PIXTURES OF HOMOSHEXJ00WALS AND J0UNGG BOYEEEZ",
			"H0LD 0NT0 J00R BITCHBUTTPUNXAYAZZ I NEED TO LIQDRINKSIP MY LAYMERSAQPASTE",
			"EYEARSEE IS DA SHYTT D00DZNUT!",
			"EYE PLAY WIF PHISHEZZ LYKE SACQUE J00STEAU",
			"SUX BUTZ NUTZ IN THA CLITSAQ JAQ AND THA BIG BLAQ MAQ DADDEEE",
			"J00VE GOT BITCHPUNX!!!",
			"GO DAMN IM BEGINNING TO CLITFUX UNDERNDASDTD YOU",
			"I GOT SHIT COMING OUT OF MY NOSE IM LAUGHING SO HARD",
			"OOPZ HEH IM SO SMAERT",
			"J00 THINK YER FUNNY SPUDZ? WELL J00 ARENT CUZ MY FREND NADSAQ JACQSON QILL KICK YOUR ASS ANYDAY",
			"MOE LESTER? IS THAT J00?",
			"OUDOOOWN, J00 R SOOO ELITTE I BET YOU CAN KIQ THE CHEEZESAQJUICE OUT OFF F TOBYEAZ",
			"DAMN 12 YR OLDZ THINK THEYRE KRADDER THAN MR AOLMAN",
			"DOHNT MAYKE ME HAFTUH PLUS BEE YER AYAZZ!!!!!!!!!",
			"HAHAHAHAH CAPS LOCK IS SO EREET, I BET R0B0C0D USES IT ALL THE TIME IN THOSE WAREZ CHANNELZ... HE SAYS LIKE \"GIVE ME WAREZ OR I WILL COLLIDE YOUR AZZ\" AND THEY JUST DO",
			"K TO THIS STUFF LIKE A BITCHPUNX TO ASSNUGGETS"
		};
	
		public string Trigger => "!aolsay";
		
		public void Action(IBot bot, string channel, string args)
		{
			bot.Client.SendMessage(Responses[Random.Next(Responses.Length)], channel);
		}
	}
}